name: finger_print_pad
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: uz.udevs.finger_print_pad
        pluginClass: FingerPrintPadPlugin
      ios:
        pluginClass: FingerPrintPadPlugin
